### ISSUE TITLE
spiralis-inbound will not run without valid azure config

### ISSUE THREAD

**Issue by tomasgr** [difi/vefa-spiralis#1]
Tried running spiralis-inbound-1.0-RC2.jar but it requires valid Azure values to be bound from .conf file.
My understading is that azure support should be optional?

Stack trace when azure config not set:
>Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:
>
>1) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=spiralis.azure.connect) was bound.
>  while locating java.lang.String annotated with @com.google.inject.name.Named(value=spiralis.azure.connect)
>    for parameter 0 at no.balder.spiralis.payload.AzurePayloadStore.<init>(AzurePayloadStore.java:33)
>  at no.balder.spiralis.config.InboundModule.configure(InboundModule.java:26)
>
>1 error
>        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
>        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
>        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
>        at com.google.inject.Guice.createInjector(Guice.java:96)
>        at com.google.inject.Guice.createInjector(Guice.java:73)
>        at com.google.inject.Guice.createInjector(Guice.java:62)
>        at no.balder.spiralis.config.InjectorHelper.getInstance(InjectorHelper.java:21)
>        at no.balder.spiralis.inbound.App.main(App.java:34)

**Comment by steinarcook** [comment]
The long term plan for Spiralis is to support various storage systems like for instance Azure, Amazon S3, your own home grown implementation and so forth.

The current version only supports Microsoft Azure, hence the "RC" (Release Candidate) version number. 

Support for other storage mechanisms is henceforth pending further development.

**Comment by tomasgr** [comment]
My mistake, I thought you could use the local filesystem for storage and just use Spiralis for handling of metadata.

Thanks for the clarification.
